-- Song voting feature: vote_sessions, vote_proposals, vote_ballots
-- Voting model: each voter ranks songs within each proposer's group separately.

-- ============================================================
-- Tables
-- ============================================================

create table public.vote_sessions (
  id                    bigint generated by default as identity primary key,
  band_id               bigint not null references public.bands (id) on delete cascade,
  name                  text not null,
  proposals_per_member  integer not null default 3,
  songs_to_add          integer not null default 3,
  status                text not null default 'proposing',
  created_by            uuid not null references auth.users (id),
  created_at            timestamptz not null default now(),
  constraint vote_sessions_status_check check (status in ('proposing','voting','completed'))
);

create table public.vote_proposals (
  id               bigint generated by default as identity primary key,
  vote_session_id  bigint not null references public.vote_sessions (id) on delete cascade,
  band_id          bigint not null references public.bands (id) on delete cascade,
  user_id          uuid not null references auth.users (id) on delete cascade,
  song_name        text not null,
  artist           text,
  spotify_url      text,
  created_at       timestamptz not null default now()
);

-- rank is per-proposer-group: within a voter's ballot, rank 1 = most preferred
-- among that proposer's songs. proposer_id denotes whose song-group is being ranked.
create table public.vote_ballots (
  id               bigint generated by default as identity primary key,
  vote_session_id  bigint not null references public.vote_sessions (id) on delete cascade,
  proposal_id      bigint not null references public.vote_proposals (id) on delete cascade,
  proposer_id      uuid not null references auth.users (id),
  user_id          uuid not null references auth.users (id) on delete cascade,
  rank             integer not null,
  created_at       timestamptz not null default now(),
  unique (vote_session_id, proposal_id, user_id),
  unique (vote_session_id, user_id, proposer_id, rank)
);

-- ============================================================
-- Row Level Security
-- ============================================================

alter table public.vote_sessions enable row level security;
alter table public.vote_proposals enable row level security;
alter table public.vote_ballots enable row level security;

-- vote_sessions: band members can view, insert, and update status
create policy "band members can view vote sessions"
  on public.vote_sessions for select
  to authenticated
  using (public.is_band_member(band_id));

create policy "band members can create vote sessions"
  on public.vote_sessions for insert
  to authenticated
  with check (public.is_band_member(band_id) and auth.uid() = created_by);

create policy "band members can update vote sessions"
  on public.vote_sessions for update
  to authenticated
  using (public.is_band_member(band_id));

create policy "band members can delete vote sessions"
  on public.vote_sessions for delete
  to authenticated
  using (public.is_band_member(band_id));

-- vote_proposals: band members can view; users manage their own
create policy "band members can view vote proposals"
  on public.vote_proposals for select
  to authenticated
  using (public.is_band_member(band_id));

create policy "band members can insert vote proposals"
  on public.vote_proposals for insert
  to authenticated
  with check (public.is_band_member(band_id) and auth.uid() = user_id);

create policy "users can delete their own vote proposals"
  on public.vote_proposals for delete
  to authenticated
  using (auth.uid() = user_id);

-- vote_ballots: band members can view; users manage their own
create policy "band members can view vote ballots"
  on public.vote_ballots for select
  to authenticated
  using (
    exists (
      select 1 from public.vote_sessions vs
      where vs.id = vote_session_id
        and public.is_band_member(vs.band_id)
    )
  );

create policy "users can insert their own vote ballots"
  on public.vote_ballots for insert
  to authenticated
  with check (
    auth.uid() = user_id and
    exists (
      select 1 from public.vote_sessions vs
      where vs.id = vote_session_id
        and public.is_band_member(vs.band_id)
    )
  );

create policy "users can delete their own vote ballots"
  on public.vote_ballots for delete
  to authenticated
  using (auth.uid() = user_id);
