-- Band invitations system

create table if not exists public.band_invitations (
  id             bigint generated by default as identity primary key,
  band_id        bigint not null references public.bands (id) on delete cascade,
  invitee_user_id uuid not null references auth.users (id) on delete cascade,
  invited_by     uuid not null references auth.users (id) on delete cascade,
  status         text not null default 'pending' check (status in ('pending', 'accepted', 'declined')),
  created_at     timestamptz not null default now(),
  unique (band_id, invitee_user_id)
);

alter table public.band_invitations enable row level security;

-- Band members can create invitations for their bands
create policy "band members can invite others"
  on public.band_invitations for insert
  to authenticated
  with check (public.is_band_member(band_id) and auth.uid() = invited_by);

-- Invitees can see their own invitations; band members can see invitations for their band
create policy "users can view relevant invitations"
  on public.band_invitations for select
  to authenticated
  using (auth.uid() = invitee_user_id or public.is_band_member(band_id));

-- Only the invitee can accept or decline
create policy "invitees can update their own invitations"
  on public.band_invitations for update
  to authenticated
  using (auth.uid() = invitee_user_id)
  with check (auth.uid() = invitee_user_id);
