-- Practice progress: personal per-user tracking of song readiness

create table if not exists public.practice_progress (
  id         bigint generated by default as identity primary key,
  song_id    bigint not null references public.songs (id) on delete cascade,
  user_id    uuid not null references auth.users (id) on delete cascade,
  band_id    bigint not null references public.bands (id) on delete cascade,
  status     text not null default 'not_ready',
  notes      text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (song_id, user_id)
);

alter table public.practice_progress enable row level security;

create policy "users can view their own practice progress"
  on public.practice_progress for select
  to authenticated
  using (auth.uid() = user_id);

create policy "users can insert their own practice progress"
  on public.practice_progress for insert
  to authenticated
  with check (auth.uid() = user_id and public.is_band_member(band_id));

create policy "users can update their own practice progress"
  on public.practice_progress for update
  to authenticated
  using (auth.uid() = user_id);

create policy "users can delete their own practice progress"
  on public.practice_progress for delete
  to authenticated
  using (auth.uid() = user_id);
