create table if not exists public.chord_charts (
  id             bigint generated by default as identity primary key,
  song_id        bigint not null unique references public.songs (id) on delete cascade,
  key            text,
  bpm            integer,
  time_signature text,
  notes          text,
  sections       jsonb not null default '[]'::jsonb,
  updated_at     timestamptz not null default now()
);

alter table public.chord_charts enable row level security;

create policy "band members can view chord charts"
  on public.chord_charts for select
  to authenticated
  using (
    exists (
      select 1 from public.songs s
      where s.id = song_id
        and public.is_band_member(s.band_id)
    )
  );

create policy "band members can insert chord charts"
  on public.chord_charts for insert
  to authenticated
  with check (
    exists (
      select 1 from public.songs s
      where s.id = song_id
        and public.is_band_member(s.band_id)
    )
  );

create policy "band members can update chord charts"
  on public.chord_charts for update
  to authenticated
  using (
    exists (
      select 1 from public.songs s
      where s.id = song_id
        and public.is_band_member(s.band_id)
    )
  );

create policy "band members can delete chord charts"
  on public.chord_charts for delete
  to authenticated
  using (
    exists (
      select 1 from public.songs s
      where s.id = song_id
        and public.is_band_member(s.band_id)
    )
  );
