-- Initial schema migration
-- Captures the manually-created database schema

-- ============================================================
-- Tables (ordered by dependency)
-- ============================================================

create table if not exists public.bands (
  id         bigint generated by default as identity primary key,
  name       text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.band_members (
  id         bigint generated by default as identity primary key,
  band_id    bigint not null references public.bands (id) on delete cascade,
  user_id    uuid not null references auth.users (id) on delete cascade,
  instrument text,
  created_at timestamptz not null default now()
);

create table if not exists public.songs (
  id         bigint generated by default as identity primary key,
  band_id    bigint not null references public.bands (id) on delete cascade,
  name       text,
  artist     text,
  duration   integer,
  created_at timestamptz not null default now()
);

create table if not exists public.setlists (
  id         bigint generated by default as identity primary key,
  band_id    bigint not null references public.bands (id) on delete cascade,
  name       text,
  created_at timestamptz not null default now()
);

create table if not exists public.setlist_songs (
  id         bigint generated by default as identity primary key,
  setlist_id bigint not null references public.setlists (id) on delete cascade,
  song_id    bigint not null references public.songs (id) on delete cascade,
  set        integer not null,
  set_weight integer not null,
  created_at timestamptz not null default now()
);

create table if not exists public.comment_types (
  id         bigint generated by default as identity primary key,
  label      text,
  created_at timestamptz not null default now()
);

create table if not exists public.song_comments (
  id              bigint generated by default as identity primary key,
  song_id         bigint not null references public.songs (id) on delete cascade,
  user_id         uuid not null references auth.users (id) on delete cascade,
  comment_type_id bigint references public.comment_types (id) on delete set null,
  comment         text,
  created_at      timestamptz not null default now()
);

create table if not exists public.user_profiles (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references auth.users (id) on delete cascade,
  first_name text,
  last_name  text,
  bio        text,
  created_at timestamptz not null default now()
);

-- ============================================================
-- Functions
-- ============================================================

create or replace function public.is_band_member(band_id_arg bigint)
returns boolean
language sql
security definer
stable
as $$
  select exists (
    select 1
    from public.band_members
    where band_id = band_id_arg
      and user_id = auth.uid()
  );
$$;

-- ============================================================
-- Row Level Security
-- ============================================================

alter table public.bands enable row level security;
alter table public.band_members enable row level security;
alter table public.songs enable row level security;
alter table public.setlists enable row level security;
alter table public.setlist_songs enable row level security;
alter table public.comment_types enable row level security;
alter table public.song_comments enable row level security;
alter table public.user_profiles enable row level security;

-- bands: band members can read; any authenticated user can create
create policy "band members can view their bands"
  on public.bands for select
  to authenticated
  using (public.is_band_member(id));

create policy "authenticated users can create bands"
  on public.bands for insert
  to authenticated
  with check (true);

-- band_members: members of the band can view; authenticated users can join
create policy "band members can view members"
  on public.band_members for select
  to authenticated
  using (public.is_band_member(band_id));

create policy "authenticated users can join bands"
  on public.band_members for insert
  to authenticated
  with check (auth.uid() = user_id);

-- songs: band members can manage songs
create policy "band members can view songs"
  on public.songs for select
  to authenticated
  using (public.is_band_member(band_id));

create policy "band members can insert songs"
  on public.songs for insert
  to authenticated
  with check (public.is_band_member(band_id));

create policy "band members can update songs"
  on public.songs for update
  to authenticated
  using (public.is_band_member(band_id));

create policy "band members can delete songs"
  on public.songs for delete
  to authenticated
  using (public.is_band_member(band_id));

-- setlists: band members can manage setlists
create policy "band members can view setlists"
  on public.setlists for select
  to authenticated
  using (public.is_band_member(band_id));

create policy "band members can insert setlists"
  on public.setlists for insert
  to authenticated
  with check (public.is_band_member(band_id));

create policy "band members can update setlists"
  on public.setlists for update
  to authenticated
  using (public.is_band_member(band_id));

create policy "band members can delete setlists"
  on public.setlists for delete
  to authenticated
  using (public.is_band_member(band_id));

-- setlist_songs: access via parent setlist's band membership
create policy "band members can view setlist songs"
  on public.setlist_songs for select
  to authenticated
  using (
    exists (
      select 1 from public.setlists s
      where s.id = setlist_id
        and public.is_band_member(s.band_id)
    )
  );

create policy "band members can insert setlist songs"
  on public.setlist_songs for insert
  to authenticated
  with check (
    exists (
      select 1 from public.setlists s
      where s.id = setlist_id
        and public.is_band_member(s.band_id)
    )
  );

create policy "band members can update setlist songs"
  on public.setlist_songs for update
  to authenticated
  using (
    exists (
      select 1 from public.setlists s
      where s.id = setlist_id
        and public.is_band_member(s.band_id)
    )
  );

create policy "band members can delete setlist songs"
  on public.setlist_songs for delete
  to authenticated
  using (
    exists (
      select 1 from public.setlists s
      where s.id = setlist_id
        and public.is_band_member(s.band_id)
    )
  );

-- comment_types: readable by all authenticated users
create policy "authenticated users can view comment types"
  on public.comment_types for select
  to authenticated
  using (true);

-- song_comments: band members can view; authors own their comments
create policy "band members can view song comments"
  on public.song_comments for select
  to authenticated
  using (
    exists (
      select 1 from public.songs s
      where s.id = song_id
        and public.is_band_member(s.band_id)
    )
  );

create policy "authenticated users can insert song comments"
  on public.song_comments for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "users can update their own song comments"
  on public.song_comments for update
  to authenticated
  using (auth.uid() = user_id);

create policy "users can delete their own song comments"
  on public.song_comments for delete
  to authenticated
  using (auth.uid() = user_id);

-- user_profiles: users own their profile; band members can view each other
create policy "users can view their own profile"
  on public.user_profiles for select
  to authenticated
  using (auth.uid() = user_id);

create policy "users can insert their own profile"
  on public.user_profiles for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "users can update their own profile"
  on public.user_profiles for update
  to authenticated
  using (auth.uid() = user_id);
